
# ==============================================================
# = Parametri Sicurezza AWS DynamoDb 
# ==============================================================
sicurezza:
    key: AKIAWAUHRQF3EA4WGGG6
    secret: XXXXXXXXXXXXXXXXXXXX

# ==============================================================
# = Nome Bucket AWS S3 in uso
# ==============================================================    
buckets:
    spese: com.xantrix.spese
    backup: com.xantrix.backup