package it.alnao.servless.selectbolUser;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName="CorsoLambdaClienti")
public class Clienti implements Serializable {
	private static final long serialVersionUID = 731426089588933520L;
	//@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName = "userId")
	private String codfid;

	@DynamoDBAttribute(attributeName = "nominativo")
	private String nominativo;
	
	@DynamoDBAttribute(attributeName = "attivo")
	private boolean attivo;
	
	@DynamoDBAttribute(attributeName = "dataCreazione")
	private String dataCreazione;	
	
	@DynamoDBAttribute(attributeName = "cards")
	private Cards cards;
}
