version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "example05-sqs"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-16f9te7yqqw7l"
s3_prefix = "example05-sqs"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
