server:
  port: 8042

aws:
    accessKey: ${AWS_ACCESS_KEY:}
    secretKey: ${AWS_SECRET_KEY:}
    region: ${AWS_REGION:eu-central-1}
    profile: ${AWS_PROFILE:}
    

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: "always"