---
AWSTemplateFormatVersion: '2010-09-09'
Description: Creazione Funzione Lambda Inserimento Dati Utente

Resources:

  IamRoleLambdaExecution:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: 'insertuser-policy'
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
      Path: "/"
      RoleName: "insertuser-role"

  InsertUserJava:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: 'alnao-lambda'
        S3Key: insert-user-0.0.1-SNAPSHOT-aws.jar
      FunctionName: InsertUserJava
      Handler: it.alnao.servless.insertUser.hendler.DataFuncionHandler
      MemorySize: 512

      Role:
        Fn::GetAtt:
        - IamRoleLambdaExecution
        - Arn

      Runtime: java8
      Timeout: 25
    DependsOn:
    - IamRoleLambdaExecution
    