
# ==============================================================
# = Parametri Sicurezza JWT 
# ==============================================================
sicurezza:
    uri: /auth
    refresh: /refresh
    header: Authorization
    prefix: Bearer 
    expiration: 86400
    secret: 123_Stella